import Head from 'next/head'
import Image from 'next/image'

import style from '@/styles/About.module.scss'
import styles from '@/styles/Home.module.scss'

// Components
import Navbar from '@/Components/navbar'
import Footer from '@/Components/footer'

export default function About() {
    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className={`${styles.main}`}>

                <div className={`${styles.hero_container} ${styles.fl_wrap} ${styles.full_height}`}>

                    <Navbar />

                    <div id={style["wrapper"]}>
                        <div className={styles.content}>
                            <div className={`${style.container} ${style.content_container}`}>
                                <div className={style.row}>
                                    {/* <div className={style.content_right}>
                                        <div className="">
                                            <div className={style.pr_bg} />
                                            <div className={`${style.fixed_column_wrap_content}`}>
                                                <div className={style.slideshow_container}>
                                                    <div className={`${style.slideshow_container_wrap} ${style.fl_wrap} ${style.full_height}`}>
                                                        <div className={`${style.swiper_container} ${style.swiper_container_fade} ${style.swiper_container_horizontal} ${style.swiper_container_android}`}>
                                                            <div className={style.swiper_wrapper}>
                                                                <div
                                                                    className={`${style.swiper_slide} ${style.swiper_slide_duplicate} ${style.swiper_slide_duplicate_next}`}
                                                                    data-swiper-slide-index={2}
                                                                    style={{
                                                                        width: 1731,
                                                                        transitionDuration: "0ms",
                                                                        opacity: 1,
                                                                        transform: "translate3d(0px, 0px, 0px)"
                                                                    }}
                                                                >
                                                                    <div
                                                                        className={`${style.ms_item_fs} ${style.fl_wrap}`}
                                                                        style={{ height: 1485 }}
                                                                    >
                                                                        <div
                                                                            className={`${style.bg} ${style.par_elem}`}
                                                                            data-bg="https://www.cssgroupsite.com/images/slider3.jpg"
                                                                            style={{
                                                                                backgroundImage:
                                                                                    'url("https://www.cssgroupsite.com/images/slider3.jpg")'
                                                                            }}
                                                                        />
                                                                    </div>
                                                                </div>
                                                                <div
                                                                    className={`${style.swiper_slide} ${style.swiper_slide_prev}`}
                                                                    data-swiper-slide-index={0}
                                                                    style={{
                                                                        width: 1731,
                                                                        transitionDuration: "0ms",
                                                                        opacity: 1,
                                                                        transform: "translate3d(-1731px, 0px, 0px)"
                                                                    }}
                                                                >
                                                                    <div
                                                                        className={`${style.ms_item_fs} ${style.fl_wrap}`}
                                                                        style={{ height: 1485 }}
                                                                    >
                                                                        <div
                                                                            className={`${style.bg} ${style.par_elem}`}
                                                                            data-bg="https://www.cssgroupsite.com/images/slider1.jpg"
                                                                            style={{
                                                                                backgroundImage:
                                                                                    'url("https://www.cssgroupsite.com/images/slider1.jpg")'
                                                                            }}
                                                                        />
                                                                    </div>
                                                                </div>
                                                                <div
                                                                    className={`${style.swiper_slide} ${style.swiper_slide_active}`}
                                                                    data-swiper-slide-index={1}
                                                                    style={{
                                                                        width: 1731,
                                                                        transitionDuration: "0ms",
                                                                        opacity: 1,
                                                                        transform: "translate3d(-3462px, 0px, 0px)"
                                                                    }}
                                                                >
                                                                    <div
                                                                        className={`${style.ms_item_fs} ${style.fl_wrap}`}
                                                                        style={{ height: 1485 }}
                                                                    >
                                                                        <div
                                                                            className={`${style.bg} ${style.par_elem}`}
                                                                            data-bg="https://www.cssgroupsite.com/images/slider2.jpg"
                                                                            style={{
                                                                                backgroundImage:
                                                                                    'url("https://www.cssgroupsite.com/images/slider2.jpg")'
                                                                            }}
                                                                        />
                                                                    </div>
                                                                </div>
                                                                <div
                                                                    className={`${style.swiper_slide} ${style.swiper_slide_next}`}
                                                                    data-swiper-slide-index={2}
                                                                    style={{
                                                                        width: 1731,
                                                                        transitionDuration: "0ms",
                                                                        opacity: 0,
                                                                        transform: "translate3d(-5194px, 0px, 0px)"
                                                                    }}
                                                                >
                                                                    <div
                                                                        className={`${style.ms_item_fs} ${style.fl_wrap}`}
                                                                        style={{ height: 1485 }}
                                                                    >
                                                                        <div
                                                                            className={`${style.bg} ${style.par_elem}`}
                                                                            data-bg="https://www.cssgroupsite.com/images/slider3.jpg"
                                                                            style={{
                                                                                backgroundImage:
                                                                                    'url("https://www.cssgroupsite.com/images/slider3.jpg")'
                                                                            }}
                                                                        />
                                                                    </div>
                                                                </div>
                                                                <div
                                                                    className={`${style.swiper_slide} ${style.swiper_slide_duplicate} ${style.swiper_slide_duplicate_prev}`}
                                                                    data-swiper-slide-index={0}
                                                                    style={{
                                                                        width: 1731,
                                                                        transitionDuration: "0ms",
                                                                        opacity: 0,
                                                                        transform: "translate3d(-6925px, 0px, 0px)"
                                                                    }}
                                                                >
                                                                    <div
                                                                        className={`${style.ms_item_fs} ${style.fl_wrap}`}
                                                                        style={{ height: 1485 }}
                                                                    >
                                                                        <div
                                                                            className={`${style.bg} ${style.par_elem}`}
                                                                            data-bg="https://www.cssgroupsite.com/images/slider1.jpg"
                                                                            style={{
                                                                                backgroundImage:
                                                                                    'url("https://www.cssgroupsite.com/images/slider1.jpg")'
                                                                            }}
                                                                        />
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <span
                                                                className={style.swiper_notification}
                                                                aria-live="assertive"
                                                                aria-atomic="true"
                                                            />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className={style.overlay} />
                                                <div className={`${style.progress_bar_wrap} ${style.bot_element}`}>
                                                    <div className={style.progress_bar} />
                                                </div>
                                                <div className={`${style.fixed_column_wrap_title} ${style.first_tile_load}`}>
                                                    <h2>About the Somax Group</h2>
                                                    <p>
                                                        The CSS Group’s determination to succeed has led us to
                                                        overcome all boundaries and weather any storm.
                                                    </p>
                                                </div>
                                                <div className={style.fixed_column_dec} />
                                                <div className={style.scroll_notifer}>Scroll Down </div>
                                                <div className={style.section_counter}>
                                                    <div className={style.sc_current}>
                                                        <span>01</span>
                                                    </div>
                                                    <div className={style.sc_total}>04</div>
                                                </div>
                                                <div className={`${style.fcwc_pagination} ${style.fcwc_wrap} ${style.swiper_pagination_clickable} ${style.swiper_pagination_bullets}`}>
                                                    <span
                                                        className={style.swiper_pagination_bullet}
                                                        tabIndex={0}
                                                        role="button"
                                                        aria-label="Go to slide 1"
                                                    />
                                                    <span
                                                        className={`${style.swiper_pagination_bullet} ${style.swiper_pagination_bullet_active}`}
                                                        tabIndex={0}
                                                        role="button"
                                                        aria-label="Go to slide 2"
                                                    />
                                                    <span
                                                        className={style.swiper_pagination_bullet}
                                                        tabIndex={0}
                                                        role="button"
                                                        aria-label="Go to slide 3"
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                    </div> */}
                                    <div className={`${style.content_left}`}>
                                        <div className={`${style.column_wrap_}`}>
                                            <div className={`${style.column_wrap_container_} ${style.fl_wrap}`}>
                                                <div className={style.col_wc_dec} />
                                                <section className={style.scroll_sec} id={style["sec1"]}>
                                                    <div className={style.container}>
                                                        <div className={style.row}>
                                                            <div className={style.col_sm_2} />
                                                            <div className={`${style.col_sm_8} ${style.mb_5}`} style={{ marginBottom: 30 }}>
                                                                <div className={`${style.dec_img} ${style.fl_wrap}`}>
                                                                    <img
                                                                        src="https://www.cssgroupsite.com/images/head-office.jpg"
                                                                        className={style.respimg}
                                                                        alt=""
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className={style.col_sm_2} />
                                                        </div>
                                                        <div className={style.row}>
                                                            <div className={style.col_sm_12}>
                                                                <br />
                                                                <br />
                                                                <div className={`${style.main_about} ${style.fl_wrap}`}>
                                                                    <div
                                                                        className={style.section_title}
                                                                        style={{ marginBottom: 20 }}
                                                                    >
                                                                        <h3>The Somax Group (TSG) is</h3>
                                                                        <p style={{ paddingBottom: 0 }}>
                                                                            A privately held group of companies, founded
                                                                            as a necessary response to the demand of Shipowners,
                                                                            Marine & Trading Companies, in its quest to find a
                                                                            dynamic, reliable & proactive Company, ready to advise
                                                                            and support them in the Ship brokerage, Maritime
                                                                            Management & trading of commodities worldwide, aiming
                                                                            to ensuring excellence in its businesses.
                                                                            <br />
                                                                            <br />
                                                                            TSG is made up of a team of high skilled professionals
                                                                            from the maritime field, which accumulates more than
                                                                            40 years of experience in the Oil & Marine Consultancy,
                                                                            so that we can guarantee a comprehensive & reliable
                                                                            range of consultancy services. We are definitely convinced
                                                                            that TSG´s highest strength is the quality of its human
                                                                            resources.
                                                                            <br />
                                                                            <br />
                                                                            Today TSG has a global network of partners enabling
                                                                            us to provide an efficient service to our clients
                                                                            wherever and whenever required.
                                                                            <br />
                                                                        </p>

                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </section>
                                                <div className={`${style.section_separator} ${style.fl_wrap}`}>
                                                    <span />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="to-top-btn to-top" style={{ display: "none" }}>
                                <i className="fal fa-long-arrow-up" />
                            </div>
                        </div>

                        <Footer />
                    </div>


                    <div className={styles.element}>
                        <div
                            className={styles.element_item}
                            style={{ transform: "translate(-50%, -50%) matrix(1, 0, 0, 1, 819, 49)" }}
                        />
                    </div>




                </div>

            </main>

        </>
    )
}
